import { z } from "zod";
import { PRODUCT_UNITS, type ProductUnit } from "./enums";
import { normalizeDigits } from "./customer";

/**
 * Admin Products input schemas (MASTER-PROMPT §39 Phase 4, page 7).
 *
 * Owner-frozen rules for this phase:
 *  - The Product model is used as it is: name, slug, categoryId, description, images (string[] —
 *    URLs only, no upload), isOrganic, isActive, sortOrder, variants. No stock, no originalPrice,
 *    no legacy metadata.
 *  - No hard delete. A product leaves use only through `isActive = false` (its own endpoint);
 *    `Variant.isAvailable` is a separate, independent level. Variants are never deleted.
 *  - `slug` is generated by the SERVER from the name when the product is created (Unicode/Persian
 *    kebab-case, ASCII numeric suffix on collision) and is never accepted from the client. It
 *    stays stable afterwards (URLs do not change when a product is renamed).
 *  - A variant price is an integer Toman value ≥ 1 (zero is not allowed). Each unit may appear
 *    only once per product.
 *  - Updating variants PRESERVES the `_id` of every existing variant: the submitted array is the
 *    complete list, existing entries are matched by `id`, entries without `id` are new.
 */

export const PRODUCT_NAME_MAX_LENGTH = 100;
export const PRODUCT_DESCRIPTION_MAX_LENGTH = 2000;
export const PRODUCT_IMAGES_MAX_COUNT = 10;
export const PRODUCT_IMAGE_URL_MAX_LENGTH = 500;
export const PRODUCT_SLUG_MAX_LENGTH = 80;
export const PRODUCT_SEARCH_MAX_LENGTH = 100;
export const PRODUCT_LIST_DEFAULT_LIMIT = 20;
export const PRODUCT_LIST_MAX_LIMIT = 100;

/** Persian presentation labels for the fixed unit registry (the enum itself is the authority). */
export const PRODUCT_UNIT_LABELS: Record<ProductUnit, string> = {
  kg: "کیلوگرم",
  gram_500: "۵۰۰ گرم",
  piece: "عدد",
  bundle: "دسته",
  box: "جعبه",
};

export const PRODUCT_DUPLICATE_UNIT_MESSAGE = "هر واحد فروش را فقط یک‌بار می‌توان برای یک محصول ثبت کرد";

/** Arabic yeh/kaf/alef-maqsura → Persian forms, whitespace collapsed and trimmed. Idempotent. */
export const normalizePersianText = (value: string): string =>
  value
    .replace(/[يى]/g, "ی")
    .replace(/ك/g, "ک")
    .replace(/\s+/g, " ")
    .trim();

/**
 * Builds the URL token for a product name. Deliberately NOT a transliteration: letters of any
 * script are kept (Persian stays Persian), Persian/Arabic digits become ASCII, diacritics/tatweel
 * are dropped, Latin is lowercased, and every run of anything else — spaces, punctuation, ZWNJ —
 * becomes a single `-`. Returns "" when the name has no letter or digit at all (the name schema
 * rejects such names, so a created product always gets a non-empty slug).
 */
export function slugifyProductName(name: string): string {
  const cleaned = normalizeDigits(normalizePersianText(name.normalize("NFKC")))
    .replace(/[\u064B-\u065F\u0670\u0640]/g, "")
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, "-")
    .replace(/^-+|-+$/g, "");
  return cleaned.slice(0, PRODUCT_SLUG_MAX_LENGTH).replace(/-+$/g, "");
}

/** `base`, then `base-2`, `base-3`… (ASCII numeric suffix). */
export const slugWithSuffix = (base: string, n: number): string => (n <= 1 ? base : `${base}-${n}`);

export const PRODUCT_SLUG_PATTERN = /^[\p{L}\p{N}]+(?:-[\p{L}\p{N}]+)*$/u;

const nameSchema = z
  .string({ required_error: "نام محصول الزامی است", invalid_type_error: "نام محصول نامعتبر است" })
  .transform(normalizePersianText)
  .refine((v) => v.length >= 1, "نام محصول الزامی است")
  .refine((v) => v.length <= PRODUCT_NAME_MAX_LENGTH, `نام محصول حداکثر ${PRODUCT_NAME_MAX_LENGTH.toLocaleString("fa-IR")} نویسه باشد`)
  .refine((v) => v.length === 0 || slugifyProductName(v) !== "", "نام محصول باید حداقل یک حرف یا عدد داشته باشد");

const objectIdString = (message: string) => z.string({ invalid_type_error: message }).trim().regex(/^[a-f0-9]{24}$/i, message);

const categoryIdSchema = objectIdString("شناسه‌ی دسته‌بندی نامعتبر است");

const descriptionSchema = z
  .string({ invalid_type_error: "توضیحات نامعتبر است" })
  .trim()
  .max(PRODUCT_DESCRIPTION_MAX_LENGTH, `توضیحات حداکثر ${PRODUCT_DESCRIPTION_MAX_LENGTH.toLocaleString("fa-IR")} نویسه باشد`);

const imageUrlSchema = z
  .string({ invalid_type_error: "نشانی تصویر نامعتبر است" })
  .trim()
  .max(PRODUCT_IMAGE_URL_MAX_LENGTH, "نشانی تصویر بیش از حد طولانی است")
  .refine((v) => {
    try {
      const u = new URL(v);
      return u.protocol === "https:" || u.protocol === "http:";
    } catch {
      return false;
    }
  }, "نشانی تصویر باید یک آدرس http/https معتبر باشد");

const imagesSchema = z
  .array(imageUrlSchema, { invalid_type_error: "تصاویر نامعتبر است" })
  .max(PRODUCT_IMAGES_MAX_COUNT, `حداکثر ${PRODUCT_IMAGES_MAX_COUNT.toLocaleString("fa-IR")} تصویر مجاز است`);

const sortOrderSchema = z
  .number({ invalid_type_error: "ترتیب نمایش باید عدد باشد" })
  .int("ترتیب نمایش باید عدد صحیح باشد")
  .min(0, "ترتیب نمایش نمی‌تواند منفی باشد")
  .max(Number.MAX_SAFE_INTEGER, "ترتیب نمایش بیش از حد بزرگ است");

const unitSchema = z.enum(PRODUCT_UNITS, { errorMap: () => ({ message: "واحد فروش نامعتبر است" }) });

const priceSchema = z
  .number({ required_error: "قیمت الزامی است", invalid_type_error: "قیمت باید عدد باشد" })
  .int("قیمت باید عدد صحیح (تومان) باشد")
  .min(1, "قیمت باید حداقل ۱ تومان باشد")
  .max(Number.MAX_SAFE_INTEGER, "قیمت بیش از حد بزرگ است");

const isAvailableSchema = z.boolean({ invalid_type_error: "وضعیت موجود بودن نامعتبر است" });

const createVariantSchema = z.object({
  unit: unitSchema,
  price: priceSchema,
  isAvailable: isAvailableSchema.optional(),
});

/** An entry with `id` updates that existing variant (unit/price/isAvailable all optional); an entry without `id` is a NEW variant (unit and price required). */
const updateVariantSchema = z
  .object({
    id: objectIdString("شناسه‌ی واحد فروش نامعتبر است").optional(),
    unit: unitSchema.optional(),
    price: priceSchema.optional(),
    isAvailable: isAvailableSchema.optional(),
  })
  .superRefine((v, ctx) => {
    if (!v.id) {
      if (v.unit === undefined) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["unit"], message: "واحد فروش الزامی است" });
      if (v.price === undefined) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["price"], message: "قیمت الزامی است" });
    }
  });

function checkVariantList(variants: { id?: string; unit?: ProductUnit }[], ctx: z.RefinementCtx) {
  const units = new Set<string>();
  const ids = new Set<string>();
  variants.forEach((v, i) => {
    if (v.unit !== undefined) {
      if (units.has(v.unit)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: [i, "unit"], message: PRODUCT_DUPLICATE_UNIT_MESSAGE });
      units.add(v.unit);
    }
    if (v.id) {
      const key = v.id.toLowerCase();
      if (ids.has(key)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: [i, "id"], message: "یک واحد فروش بیش از یک‌بار ارسال شده است" });
      ids.add(key);
    }
  });
}

const createVariantsSchema = z
  .array(createVariantSchema, { required_error: "حداقل یک واحد فروش لازم است", invalid_type_error: "واحدهای فروش نامعتبر است" })
  .min(1, "حداقل یک واحد فروش لازم است")
  .superRefine((variants, ctx) => checkVariantList(variants, ctx));

const updateVariantsSchema = z
  .array(updateVariantSchema, { invalid_type_error: "واحدهای فروش نامعتبر است" })
  .min(1, "حداقل یک واحد فروش لازم است")
  .superRefine((variants, ctx) => checkVariantList(variants, ctx));

/** Unknown keys (slug, id, createdAt…) are stripped on create — the server never trusts a client slug. */
export const createProductSchema = z.object({
  name: nameSchema,
  categoryId: categoryIdSchema,
  description: descriptionSchema.optional(),
  images: imagesSchema.optional(),
  isOrganic: z.boolean({ invalid_type_error: "وضعیت ارگانیک نامعتبر است" }).optional(),
  isActive: z.boolean({ invalid_type_error: "وضعیت فعال/غیرفعال نامعتبر است" }).optional(),
  sortOrder: sortOrderSchema.optional(),
  variants: createVariantsSchema,
});

const EDITABLE_KEYS = ["name", "categoryId", "description", "images", "isOrganic", "sortOrder", "variants"] as const;
const READ_ONLY_KEYS = ["slug", "isActive", "id", "_id", "createdAt", "updatedAt", "category"] as const;

/**
 * PATCH body. Only the keys above can change. `slug` (server-generated), `isActive` (own
 * endpoint) and any other key are REJECTED with 400 — nothing is silently dropped. `description: ""`
 * clears the description. At least one editable field is required.
 */
export const updateProductSchema = z
  .object({
    name: nameSchema.optional(),
    categoryId: categoryIdSchema.optional(),
    description: descriptionSchema.optional(),
    images: imagesSchema.optional(),
    isOrganic: z.boolean({ invalid_type_error: "وضعیت ارگانیک نامعتبر است" }).optional(),
    sortOrder: sortOrderSchema.optional(),
    variants: updateVariantsSchema.optional(),
  })
  .passthrough()
  .superRefine((v, ctx) => {
    for (const key of Object.keys(v)) {
      if ((EDITABLE_KEYS as readonly string[]).includes(key)) continue;
      const known = (READ_ONLY_KEYS as readonly string[]).includes(key);
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: [key],
        message: known ? `فیلد «${key}» قابل ویرایش نیست` : `فیلد «${key}» نامعتبر است`,
      });
    }
    if (!EDITABLE_KEYS.some((k) => v[k] !== undefined)) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: "حداقل یک فیلد برای ویرایش لازم است" });
    }
  })
  .transform((v) => {
    const out: {
      name?: string;
      categoryId?: string;
      description?: string;
      images?: string[];
      isOrganic?: boolean;
      sortOrder?: number;
      variants?: { id?: string; unit?: ProductUnit; price?: number; isAvailable?: boolean }[];
    } = {};
    for (const key of EDITABLE_KEYS) if (v[key] !== undefined) (out as Record<string, unknown>)[key] = v[key];
    return out;
  });

export const productStatusSchema = z.object({
  isActive: z.boolean({ required_error: "وضعیت فعال/غیرفعال الزامی است", invalid_type_error: "وضعیت باید فعال یا غیرفعال باشد" }),
});

const booleanQuery = (message: string) =>
  z
    .enum(["true", "false"], { errorMap: () => ({ message }) })
    .transform((v) => v === "true")
    .optional();

export const productListQuerySchema = z.object({
  page: z.coerce
    .number({ invalid_type_error: "شماره‌ی صفحه نامعتبر است" })
    .int("شماره‌ی صفحه باید عدد صحیح باشد")
    .min(1, "شماره‌ی صفحه باید حداقل ۱ باشد")
    .max(1_000_000, "شماره‌ی صفحه بیش از حد بزرگ است")
    .default(1),
  limit: z.coerce
    .number({ invalid_type_error: "تعداد در صفحه نامعتبر است" })
    .int("تعداد در صفحه باید عدد صحیح باشد")
    .min(1, "تعداد در صفحه باید حداقل ۱ باشد")
    .max(PRODUCT_LIST_MAX_LIMIT, `تعداد در صفحه حداکثر ${PRODUCT_LIST_MAX_LIMIT} باشد`)
    .default(PRODUCT_LIST_DEFAULT_LIMIT),
  search: z
    .string()
    .trim()
    .max(PRODUCT_SEARCH_MAX_LENGTH, `عبارت جست‌وجو حداکثر ${PRODUCT_SEARCH_MAX_LENGTH} نویسه باشد`)
    .transform((v) => normalizeDigits(normalizePersianText(v)).toLowerCase())
    .transform((v) => (v === "" ? undefined : v))
    .optional(),
  categoryId: objectIdString("شناسه‌ی دسته‌بندی نامعتبر است").optional(),
  isActive: booleanQuery("فیلتر وضعیت نامعتبر است"),
  isOrganic: booleanQuery("فیلتر ارگانیک نامعتبر است"),
});

export type CreateProductInput = z.infer<typeof createProductSchema>;
export type UpdateProductInput = z.infer<typeof updateProductSchema>;
export type ProductListQuery = z.infer<typeof productListQuerySchema>;

/** What a client may send (the schemas' input side; the server re-validates). */
export interface CreateProductRequest {
  name: string;
  categoryId: string;
  description?: string;
  images?: string[];
  isOrganic?: boolean;
  isActive?: boolean;
  sortOrder?: number;
  variants: { unit: ProductUnit; price: number; isAvailable?: boolean }[];
}

export interface UpdateProductRequest {
  name?: string;
  categoryId?: string;
  description?: string;
  images?: string[];
  isOrganic?: boolean;
  sortOrder?: number;
  /** The complete variant list: entries with `id` keep their identity, entries without are new. */
  variants?: { id?: string; unit?: ProductUnit; price?: number; isAvailable?: boolean }[];
}

/**
 * The rules every FINAL variant list must satisfy, whatever produced it (create, or an update merged
 * with the existing variants). Returns the first Persian error message, or null.
 */
export function validateVariantSet(variants: { unit: string; price: number }[]): string | null {
  if (variants.length === 0) return "حداقل یک واحد فروش لازم است";
  const seen = new Set<string>();
  for (const v of variants) {
    if (!(PRODUCT_UNITS as readonly string[]).includes(v.unit)) return "واحد فروش نامعتبر است";
    if (!Number.isInteger(v.price) || v.price < 1) return "قیمت باید یک عدد صحیح و حداقل ۱ تومان باشد";
    if (seen.has(v.unit)) return PRODUCT_DUPLICATE_UNIT_MESSAGE;
    seen.add(v.unit);
  }
  return null;
}

export interface ProductVariantDto {
  id: string;
  unit: ProductUnit;
  price: number;
  isAvailable: boolean;
}

export interface ProductCategoryDto {
  id: string;
  name: string;
  isActive: boolean;
}

export interface ProductDto {
  id: string;
  name: string;
  slug: string;
  /** null only if the referenced category document no longer exists. */
  category: ProductCategoryDto | null;
  description: string | null;
  images: string[];
  isOrganic: boolean;
  isActive: boolean;
  sortOrder: number;
  variants: ProductVariantDto[];
  createdAt: string;
  updatedAt: string;
}

export interface ProductListResult {
  items: ProductDto[];
  pagination: { page: number; pageSize: number; total: number };
}
