import type { NextRequest } from "next/server";
import { createProductSchema, productListQuerySchema } from "@fruitland/shared";
import { apiErrorFromException, apiSuccess } from "@/lib/server/apiResponse";
import { connectToDatabase } from "@/lib/server/db";
import { requireAdmin } from "@/lib/server/auth/guard";
import { createProduct, listProducts } from "@/lib/server/services/productService";
import { parseJsonBody } from "@/lib/server/validation/parseJsonBody";
import { parseQuery } from "@/lib/server/validation/parseQuery";

/**
 * GET /api/v1/admin/products?page&limit&search&categoryId&isActive&isOrganic — Auth: admin/master_admin. page ≥ 1; limit 1–100 (default 20);
 * search ≤ 100 chars over name/slug (escaped, never a raw regex); categoryId an ObjectId; isActive/isOrganic "true"|"false" (omitted = all).
 * Ordered by sortOrder, name, _id. Response: DTO list + envelope `pagination {page,pageSize,total}`.
 */
export async function GET(request: NextRequest) {
  try {
    requireAdmin(request);
    const query = parseQuery(request, productListQuerySchema);
    await connectToDatabase();
    const { items, pagination } = await listProducts(query);
    return apiSuccess(items, { pagination });
  } catch (err) {
    return apiErrorFromException(err);
  }
}

/**
 * POST /api/v1/admin/products — Auth: admin/master_admin. Body: { name, categoryId (must be an ACTIVE category), description?, images? (http/https URLs),
 * isOrganic?, isActive?, sortOrder?, variants (≥ 1; unit once each; price integer Toman ≥ 1; isAvailable?) }. The slug is generated by the server
 * from the name (a client slug is ignored). 400 PRODUCT_CATEGORY_INVALID / PRODUCT_VARIANTS_INVALID; 409 PRODUCT_SLUG_CONFLICT. Audited.
 */
export async function POST(request: NextRequest) {
  try {
    const { userId } = requireAdmin(request);
    const input = await parseJsonBody(request, createProductSchema);
    await connectToDatabase();
    return apiSuccess(await createProduct(userId, input), { message: "محصول ایجاد شد", status: 201 });
  } catch (err) {
    return apiErrorFromException(err);
  }
}
